# Page settings
baseurl = "http://example.org/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

# Enable HTML tags in markdown renderer, for example for line breaks <br>
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]

  # Theme styles
  # The original template comes with 6 colour schemes. You may choose styles below.
  # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
  # are available. Also the source LESS files are included so
  # itâ€™s quick and easy to change the styling and colour scheme.
  styles = "styles-1.css"

  # If you'd like to place the sidebar on the left, you can activate it here:
  sidebarOnLeft = false

  # Name of the avatar image file
  avatar = "profile.png"

  # Footer section
  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution,
  # you can check out other license options via template author's website: themes.3rdwavemedia.com
  copyright = ""


# This theme has a multi-language feature build-in.
# In order to provide your resume in different languages, just copy the whole
# [languages.en] block below and adjust it for the next language for example
# for German replace all [languages.en.*] to [languages.de.*] and adjust the
# titles and contents accordingly.
# You can also enable or disable some features below on a per-language basis.
[languages]
  [languages.en]
    [languages.en.params]
      # Meta
      author = "Pavel Kanyshev"
      title = "John Doe Resume"
      description = "Hugo Responsive Resume/CV Theme for Developers"
      keywords = ['hugo', 'Theme', 'CV', 'Resume', '@aerohub', '@Lednerb', 'less', 'open source']

      # Sidebar sections
      # Profile section
      [languages.en.params.profile]
        name = "John Doe"
        tagline = "Full Stack Developer"
        avatar = "profile.png"

      # Contact section
      [languages.en.params.contact]
        enable = true

        [[languages.en.params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto:yourname@example.org"
        title = "john.doe@example.org"

        [[languages.en.params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+1234567890"
        title = "+1234567890"

        [[languages.en.params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "https://example.org"
        title = "portfoliosite.com"

        [[languages.en.params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/johndoe"
        title = "linkedin.com/in/johndoe"

        [[languages.en.params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/username"
        title = "github.com/username"

        [[languages.en.params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/username"
        title = "@twittername"

      # Education section
      [languages.en.params.education]
        enable = true
        title = "Education"

        [[languages.en.params.education.list]]
        degree = "MSc in Computer Science"
        college = "University of London"
        dates = "2006 - 2010"

        [[languages.en.params.education.list]]
        degree = "BSc in Applied Mathematics"
        college = "Bristol University"
        dates = "2007 - 2011"

      # Languages section
      [languages.en.params.language]
        enable = true
        title = "Languages"

        [[languages.en.params.language.list]]
        language = "English"
        level = "Native"

        [[languages.en.params.language.list]]
        language = "French"
        level = "Professional"

        [[languages.en.params.language.list]]
        language = "Russian"
        level = "Professional"

      # Interests section
      [languages.en.params.interests]
        enable = true
        title = "Interests"

        [[languages.en.params.interests.list]]
        interest = "Climbing"

        [[languages.en.params.interests.list]]
        interest = "Snowboarding"

        [[languages.en.params.interests.list]]
        interest = "Cooking"

      # Downloads section
      [languages.en.params.downloads]
        enable = true
        title = "Downloads"

        [[languages.en.params.downloads.list]]
        icon = "fa-key"
        name = "OpenPGP Key"
        filepath = "/path/to/openpgp-public-key.asc"

        [[languages.en.params.downloads.list]]
        name = "CV / Resume"
        icon = "fa-file-pdf-o"
        filepath = "/path/to/resume.pdf"

      # Main body sections
      # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)
      # Summary section
      [languages.en.params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        keywordsAsTags = true
        summary = "**Summarise your career here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu."

      # Experiences section
      [languages.en.params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[languages.en.params.experiences.list]]
        position = "Lead Developer"
        dates = "2015 - Present"
        company = "Startup Hubs, San Francisco"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."

        [[languages.en.params.experiences.list]]
        position = "Senior Software Engineer"
        dates = "2014 - 2015"
        company = "Google, London"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

        [[languages.en.params.experiences.list]]
        position = "UI Developer"
        dates = "2012 - 2014"
        company = "Amazon, London"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

      # Projects section
      [languages.en.params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[languages.en.params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[languages.en.params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "You may use this theme for building very simple FAQs or note lists."

        [[languages.en.params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[languages.en.params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[languages.en.params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

      # Skills section
      [languages.en.params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[languages.en.params.skills.list]]
        skill = "Python & Django"
        level = "98%"

        [[languages.en.params.skills.list]]
        skill = "Javascript & jQuery"
        level = "98%"

        [[languages.en.params.skills.list]]
        skill = "Angular"
        level = "95%"

        [[languages.en.params.skills.list]]
        skill = "HTML5 & CSS"
        level = "95%"

        [[languages.en.params.skills.list]]
        skill = "Ruby on Rails"
        level = "75%"

        [[languages.en.params.skills.list]]
        skill = "Sketch & Photoshop"
        level = "60%"
